### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nathancfox** [jmackie4/elpatron#1]
Hi, I was looking for a time conversion function and `hhmmss()` works perfectly, but the install instructions are failing, and there's not a clear LICENSE that allows me to copy the code and use it on my own, like a GPL or an MIT License. Can you update the License so there are no issues with the code being open source? Or if you don't want to make it open source, please update the install so that it works? I'm getting the following error in `R version 3.6.0`

```
Error: Failed to install 'unknown package' from GitHub:
  An unknown option was passed in to libcurl
```

**Comment by jmackie** [comment]
Hi there! The code is MIT licensed (see DESCRIPTION) but very much unmaintained. You're more than welcome to take whatever parts of it are useful to you though - you have my permission (or whatever legal jargon I'm supposed to say).
